import { execSync, spawn } from 'child_process';
import fs from 'fs';
import path from 'path';

/**
 * Check if Fastlane is installed and available.
 */
export function isFastlaneAvailable() {
  try {
    execSync('fastlane --version', { stdio: 'pipe' });
    return true;
  } catch {
    return false;
  }
}

/**
 * Get Fastlane version string.
 */
export function getFastlaneVersion() {
  try {
    return execSync('fastlane --version 2>&1').toString().trim().split('\n').pop();
  } catch {
    return null;
  }
}

/**
 * Run a Fastlane lane with real-time output via Socket.IO.
 */
export function runFastlaneLane({ lane, platform, workDir, env }, onOutput) {
  return new Promise((resolve, reject) => {
    if (!isFastlaneAvailable()) {
      return reject(new Error('Fastlane이 설치되어 있지 않습니다. `gem install fastlane` 또는 `brew install fastlane`으로 설치해 주세요.'));
    }

    const args = [lane];
    if (platform) {
      args.unshift(platform);
    }

    const proc = spawn('fastlane', args, {
      cwd: workDir || process.cwd(),
      stdio: ['pipe', 'pipe', 'pipe'],
      env: { ...process.env, ...env },
    });

    let stdout = '';
    let stderr = '';

    proc.stdout.on('data', (data) => {
      const text = data.toString();
      stdout += text;
      onOutput?.({ type: 'stdout', text: text.trim() });
    });

    proc.stderr.on('data', (data) => {
      const text = data.toString();
      stderr += text;
      onOutput?.({ type: 'stderr', text: text.trim() });
    });

    proc.on('close', (code) => {
      if (code === 0) {
        resolve({ success: true, output: stdout });
      } else {
        reject(new Error(`Fastlane 종료 코드 ${code}: ${stderr || stdout}`));
      }
    });

    proc.on('error', (err) => {
      reject(new Error(`Fastlane 실행 실패: ${err.message}`));
    });
  });
}

/**
 * Generate a minimal Fastfile for the project.
 */
export function generateFastfile(workDir, { platform, bundleId, scheme }) {
  const fastlaneDir = path.join(workDir, 'fastlane');
  fs.mkdirSync(fastlaneDir, { recursive: true });

  const content = `# Auto-generated by AppDeploy
default_platform(:${platform || 'ios'})

platform :ios do
  desc "Build iOS app"
  lane :build do
    build_app(
      scheme: "${scheme || 'App'}",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "App.ipa"
    )
  end

  desc "Upload to App Store via deliver"
  lane :upload_metadata do
    deliver(
      app_identifier: "${bundleId || 'com.example.app'}",
      skip_binary_upload: true,
      skip_screenshots: true,
      force: true,
      metadata_path: "./metadata"
    )
  end

  desc "Upload screenshots"
  lane :upload_screenshots do
    deliver(
      app_identifier: "${bundleId || 'com.example.app'}",
      skip_binary_upload: true,
      skip_metadata: true,
      force: true,
      screenshots_path: "./screenshots"
    )
  end
end

platform :android do
  desc "Upload to Google Play via supply"
  lane :upload_metadata do
    supply(
      package_name: "${bundleId || 'com.example.app'}",
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      metadata_path: "./metadata/android"
    )
  end

  desc "Upload screenshots to Google Play"
  lane :upload_screenshots do
    supply(
      package_name: "${bundleId || 'com.example.app'}",
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_metadata: true,
      metadata_path: "./metadata/android"
    )
  end
end
`;

  fs.writeFileSync(path.join(fastlaneDir, 'Fastfile'), content, 'utf-8');
  return path.join(fastlaneDir, 'Fastfile');
}

/**
 * Run Fastlane deliver/supply for metadata upload.
 * Uses the Fastlane metadata files already generated by /api/sync/metadata.
 */
export async function fastlaneMetadataSync({ platform, workDir, env }, onOutput) {
  const lane = 'upload_metadata';

  // Generate Fastfile if not exists
  const fastfilePath = path.join(workDir, 'fastlane', 'Fastfile');
  if (!fs.existsSync(fastfilePath)) {
    generateFastfile(workDir, { platform, bundleId: env?.BUNDLE_ID });
  }

  return runFastlaneLane({ lane, platform, workDir, env }, onOutput);
}
